version: '3.9'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=focus
      - MONGO_INITDB_ROOT_PASSWORD=TelecommFCS5055
      - MONGO_INITDB_DATABASE=focus-elevaodres
